version: 2

references:

  workspace_root: &workspace_root
      ~/code

  container_config: &container_config
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: *workspace_root

    environment:
      JVM_OPTS: "-Xmx3200m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
    key: weatherforecast-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  build:
    <<: *container_config
    resource_class: medium+
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Setup dependencies
          command: ./gradlew --no-daemon --stacktrace androidDependencies

      - run:
          name: Initial build
          command: ./gradlew --no-daemon --stacktrace assembleRelease

      - store_artifacts:
          path: ~/code/app/build/outputs/apk/
          destination: apks/

      - store_artifacts:
          path: ~/code/app/build/outputs/mapping/
          destination: mapping/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

      - save_cache:
          <<: *general_cache_key
          paths:
            - "~/.gradle"
            - "~/.m2"
            - "/opt/android-sdk-linux/licenses/"

  check:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Checks
          command: ./gradlew --no-daemon --stacktrace lintRelease checkRelease

      - store_artifacts:
          path: ~/code/app/build/reports/
          destination: lint_reports/app/

      - store_artifacts:
          path: ~/code/base/build/reports/
          destination: lint_reports/base/

  test:
    <<: *container_config
    parallelism: 3
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Tests
          command: |
            export CODECOV_REPORT_LOCATION=app/build/reports/jacoco/testReleaseUnitTestCoverage/testReleaseUnitTestCoverage.xml
            export TEST_GROUP_INDEX=${CIRCLE_NODE_INDEX}
            export TEST_GROUPS_COUNT=${CIRCLE_NODE_TOTAL}
            echo "Running test group ${TEST_GROUP_INDEX} out of ${TEST_GROUPS_COUNT}..."
            ./gradlew --no-daemon --stacktrace testReleaseUnitTest
            if [[ -f $CODECOV_REPORT_LOCATION ]]; then
              curl https://codecov.io/bash -o codecov.sh
              chmod +x codecov.sh
              ./codecov.sh -X gcov -X coveragepy -f ${CODECOV_REPORT_LOCATION}
            fi

      - store_artifacts:
          path: app/build/reports/tests/
          destination: tests_reports/

      - store_test_results:
          path: ~/code/app/build/test-results

workflows:

  version: 2

  build_check_tests_deploy:
    jobs:
      - build
      - check:
          requires:
            - build
      - test:
          requires:
            - build